MbmStore-start/MbmStore/Controllers/InvoiceController.cs
using MbmStore.DAL;
using MbmStore.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MbmStore.Controllers
{
    public class InvoiceController : Controller
    {
        private MbmStoreContext db;

        // constructor
        // instantiale a new db object
        public InvoiceController()
        {
            db = new MbmStoreContext();
        }
        // GET: Invoice
        public ActionResult Index()
        {
            ViewBag.Invoices = db.Invoices;


            // generete dropdown list
            List<SelectListItem> customers = new List<SelectListItem>();
            foreach (Invoice invoice in db.Invoices)
            {
                customers.Add(new SelectListItem { Text = invoice.Customer.Firstname + " " + invoice.Customer.Lastname, Value = invoice.Customer.CustomerId.ToString() });
            }
            // removes duplicate entries with same ID from a IEnumerable
            customers = customers.GroupBy(x => x.Value).Select(y => y.First()).OrderBy(z => z.Text).ToList<SelectListItem>();

            ViewBag.CustomerId = customers;
            return View();
        }


        [HttpPost]
        public ActionResult Index(int? CustomerId)
        {
            // generete dropdown list
            List<SelectListItem> customers = new List<SelectListItem>();
            foreach (Invoice invoice in db.Invoices)
            {
                customers.Add(new SelectListItem { Text = invoice.Customer.Firstname + " " + invoice.Customer.Lastname, Value = invoice.Customer.CustomerId.ToString() });

            }

            // removes duplicate entries with same ID from a IEnumerable
            customers = customers.GroupBy(x => x.Value).Select(y => y.First()).OrderBy(z => z.Text).ToList<SelectListItem>();

            ViewBag.CustomerID = customers;

            IEnumerable<Invoice> invoices = db.Invoices;

            if (CustomerId != null)
            {
                // select invoices for a customer with linq
                invoices = db.Invoices.Where(r => r.Customer.CustomerId == CustomerId);
            }
            ViewBag.Invoices = invoices;

            return View();
        }
    }
}

MbmStore-start/MbmStore/Controllers/NavController.cs
using MbmStore.DAL;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MbmStore.Controllers
{
    public class NavController : Controller
    {
        private MbmStoreContext db;

        // constructor
        // instantiale a new db object
        public NavController()
        {
            db = new MbmStoreContext();
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = db.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

MbmStore-start/MbmStore/Views/Nav/Menu.cshtml
@model IEnumerable<string>


        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("MBM-Store", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <ul class="nav navbar-nav">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    Products
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">

                    @foreach (var link in Model)
                    {
                        <li>
                            @Html.RouteLink(link, new
                       {
                           controller = "Catalogue",
                           action = "Index",
                           category = link,
                           page = 1
                       })
                    </li>

                    }

                </ul>
            <li>
                @Html.ActionLink("Invoices", "Index", "Invoice")
            </li>
        </ul>