MbmStore-start/MbmStore/Models/Book.cs
using System.ComponentModel.DataAnnotations.Schema;


namespace MbmStore.Models
{
    [Table("Book")]
    public class Book : Product 
    {

        public string Author { get; set; }
        public string Publisher { get; set; }
        public short Published { get; set; }
        public string ISBN { get; set; }
        public string tmp { get; set; }


        public Book() { }

        public Book(int productId, string author, string title, string imageUrl, decimal price, short published) : base(title, price, productId)
        {
            Author = author;
            ImageUrl = imageUrl;
            Published = published;
        }

    }
}

MbmStore-start/MbmStore/Models/Movie.cs
using System.ComponentModel.DataAnnotations.Schema;


namespace MbmStore.Models
{
    [Table("Movie")]
    public class Movie : Product
    {

        
        private string director;

        public string Director
        {
            get { return director; } 
            set { director = value; } 
        }

        // constructors
        public Movie() { }

        public Movie (int productId, string title, decimal price, string imageUrl, string director) : base(title, price, productId)
        {
            ImageUrl = imageUrl;
            Director = director;
      
        }
    }
}

MbmStore-start/MbmStore/Models/MusicCD.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MbmStore.Models
{
    [Table("MusicCD")]
    public class MusicCD : Product
    {
        //create list of tracks
        private List<Track> tracks = new List<Track>();


        //MusicCD properties
        public string Artist { get; set; }
        public string Label { get; set; }
        public short Released { get; set; }

        public virtual List<Track> Tracks
        {
            get { return tracks; }
            set { tracks = value; }
        }




        //Music CD constructer
        public MusicCD() { }

        public MusicCD(int productId, string artist, string title, string imageurl, decimal price, short released) : base(title, price, productId)
        {

            Artist = artist;
            ImageUrl = imageurl;         
            Released = released; 
            Tracks = tracks;
        }


        //Add Track Method
        public void AddTrack(Track track)
        {
            Tracks.Add(track);
        }

        // TimeSpam Method
        public TimeSpan GetPlayingTime()
        {
            TimeSpan playingTime = new TimeSpan(0, 0, 0);

            foreach (Track track in tracks)
            {
                playingTime += track.Length;
            }

            return playingTime;
        }

    }
}

MbmStore-start/MbmStore/Controllers/NavController.cs
using MbmStore.DAL;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MbmStore.Controllers
{
    public class NavController : Controller
    {
        private MbmStoreContext db;

        // constructor
        // instantiale a new db object
        public NavController()
        {
            db = new MbmStoreContext();
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = db.Products
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

MbmStore-start/MbmStore/Views/Shared/_Books.cshtml
@model MbmStore.Models.Book

<div class="row bottom-buffer">
    <div class="container panel panel-default">
        <div class="col-lg-8">
            <h2 class="panel-heading">@Model.Title</h2>
            <div class="panel-body">
                <h4>Author: @Model.Author</h4>
                <h4>Published: @Model.Published</h4>
                <h4>Price: @String.Format("{0:0.00}", Model.Price)</h4>
                @using (Html.BeginForm("AddToCart", "Cart"))
                {
                    @Html.Hidden("ProductId", Model.ProductId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)

                    <div class="form-group" style="height:20px;">
                        @{ var quantity = new SelectList(Enumerable.Range(1, 10)); }
                        @Html.DropDownList("Quantity", quantity, new { @class = "form-control pull-left" })
                    </div>
                    <br />
                    <div style="display:block;">
                        <input type="submit" class="btn btn-info" value="Add to cart" />
                    </div>
                            }
            </div>
        </div>
        <div class="col-lg-4">
            <img class="img-responsive" src="/Content/Images/@Model.ImageUrl" alt="@Model.Title" />
        </div>
    </div>
</div>

MbmStore-start/MbmStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-custom.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/popper.min.js"></script>
    <script src="https://use.fontawesome.com/edb4406c2f.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</head>
<body>
   
    @Html.Partial("_NavBar")

      
     <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Business Academy Aarhus</p>
        </footer>
    </div>


</body>
</html>

MbmStore-start/MbmStore/Views/Shared/_Movies.cshtml
@model MbmStore.Models.Movie

<div class="row bottom-buffer">
    <div class="container panel panel-default">
        <div class="col-lg-8">
            <h2 class="panel-heading">@Model.Title</h2>
            <div class="panel-body">
                <h4>Director: @Model.Director</h4>
                <h4>Price: @String.Format("{0:0.00}", Model.Price)</h4>
                @using (Html.BeginForm("AddToCart", "Cart"))
                {
                    @Html.Hidden("ProductId", Model.ProductId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)

                    <div class="form-group" style="height:20px;">                        
                        @{ var quantity = new SelectList(Enumerable.Range(1, 10)); }
                        @Html.DropDownList("Quantity", quantity, new { @class = "form-control pull-left" })
                    </div>
                    <br />
                    <div style="display:block;">
                        <input type="submit" class="btn btn-info" value="Add to cart" />
                    </div>
                            }
            </div>
        </div>
        <div class="col-lg-4">
            <img class="img-responsive" src="/Content/Images/@Model.ImageUrl" alt="@Model.Title" />
        </div>
    </div>
</div>

MbmStore-start/MbmStore/Views/Shared/_MusicCDs.cshtml
@using MbmStore.Models
@model MbmStore.Models.MusicCD




<div class="row bottom-buffer">
    <div class="container panel panel-default">
        <div class="col-lg-8">
            <h2 class="panel-heading">@Model.Title</h2>
            <div class="panel-body">
                <h4>Name: @Model.Artist</h4>
                <h4>Price: @String.Format("{0:0.00}", Model.Price)</h4>

                      @foreach (Track track in Model.Tracks)
                       {
                           <div class="row">
                               <div class="col-xs-4">
                                   @track.Title <br />
                               </div>
                               <div class="col-xs-4">
                                   @track.Length <br />
                               </div>
                               <div class="col-xs-4">
                                   @track.Composer <br />
                               </div>
                           </div>
                           <br />
                       } 

                <h4>Play time:@Model.GetPlayingTime()</h4>
                @using (Html.BeginForm("AddToCart", "Cart"))
                {
                    @Html.Hidden("ProductId", Model.ProductId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)

                    <div class="form-group" style="height:20px;">
                        @{ var quantity = new SelectList(Enumerable.Range(1, 10)); }
                        @Html.DropDownList("Quantity", quantity, new { @class = "form-control pull-left" })
                    </div>
                    <br />
                    <div style="display:block;">
                        <input type="submit" class="btn btn-info" value="Add to cart" />
                    </div>
                            }
            </div>
        </div>
        <div class="col-lg-4">
            <img class="img-responsive" src="/Content/Images/@Model.ImageUrl" alt="@Model.Title" />
        </div>
    </div>

</div>

MbmStore-start/MbmStore/Views/Shared/_NavBar.cshtml
@using MbmStore.Controllers;

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">

        @Html.Action("Menu", "Nav")

        @Html.Action("CartItems", "Cart")

    </div>
</div>