MbmStore-start/MbmStore/ViewModels/Cart.cs
using MbmStore.Models;
using System.Collections.Generic;
using System.Linq;

namespace MbmStore.ViewModels
{
    public class Cart
    {
        //FIELDS
        private List<CartLine> lines = new List<CartLine>();

        //PROPERTIES
        public decimal TotalPrice
        {
            get
            {
                return lines.Sum(e => e.Product.Price * e.Quantity);
            }
        }
        public List<CartLine> Lines
        {
            get
            {
                return lines;
            }
        }

        public Cart() { }

        public void AddItem(Product product, int quantity)
        {
            CartLine item = lines.Where(p => p.Product.ProductId == product.ProductId).FirstOrDefault();
            if (item == null)
            {
                lines.Add(new CartLine { Product = product, Quantity = quantity });
            }
            else
            {
                item.Quantity += quantity;
            }
        }

        public void RemoveItem(Product product)
        {
            lines.RemoveAll(i => i.Product.ProductId == product.ProductId);
        }

        public void Clear()
        {
            lines.Clear();
        }
    }
}

MbmStore-start/MbmStore/Controllers/CartController.cs
using MbmStore.Infrastructure;
using MbmStore.Models;
using MbmStore.ViewModels;
using System;
using System.Linq;
using System.Web.Mvc;
using MbmStore.DAL;

namespace MbmStore.Controllers
{
    public class CartController: Controller
    {
        private MbmStoreContext db;
        public CartController()
        {
            db = new MbmStoreContext();
        }

        public PartialViewResult CartItems(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = db.Products.FirstOrDefault(p => p.ProductId == productId);
            int quantity = 1;

            if (Request["quantity"] != null)
            {
                quantity = Int32.Parse(Request["quantity"]);
            }

            if (product != null)
            {
                GetCart().AddItem(product, quantity);
            }
            return RedirectToAction("Index", new { controller = returnUrl.Substring(1) });
            
                
        }
        
        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = db.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null) { GetCart().RemoveItem(product);
            }
            return RedirectToAction("Index", new { controller = "Cart" });
        }

        private Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"]; if (cart == null)
            {
                cart = new Cart(); Session["Cart"] = cart;
            }
            return cart;
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                // order processing logic
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }



    }
}

MbmStore-start/MbmStore/Controllers/CatalogueController.cs
using MbmStore.Infrastructure;
using MbmStore.DAL;
using MbmStore.ViewModels;
using System.Linq;
using System.Web.Mvc;
namespace MbmStore.Controllers
{
    public class CatalogueController : Controller
    {
        private MbmStoreContext db;
        public int PageSize = 2;
        // GET: Catalogue
        public ActionResult Index(string category, int page = 1)
        {
            db = new MbmStoreContext();
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = db.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize).ToList(),

               /* Products.Join(Something
                                 ProductId => MusicCD.ProductId,
                                 Track => Track.MusicCD_ProductId,
                                 (ProductId, Track) => tracks).ToList(); */


            PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                    db.Products.Count() :
                    db.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
    }
}

MbmStore-start/MbmStore/Views/Cart/CartItems.cshtml
@model MbmStore.ViewModels.Cart

<!--
<div class="navbar-right" style="padding-right:20px">
    @Html.ActionLink("Checkout", "Index", "Cart",
        new { returnUrl = Request.Url.PathAndQuery },
        new { @class = "btn btn-default navbar-btn" })
</div>
-->
      

<ul class="nav navbar-nav navbar-right">
    @using (Html.BeginForm("Index", "Cart"))
            {
        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
        <button class="cart" type="submit" value="View Cart" style="background-color: transparent; color:white;padding-top: 10px; padding-bottom:10px; border: 0;">
            
            @Model.Lines.Sum(x => x.Quantity) item(s),
            @Model.TotalPrice.ToString("n")€
            <i class="fa fa-shopping-cart fa-2x"></i>

        </button>
    }
</ul>

MbmStore-start/MbmStore/Views/Cart/Checkout.cshtml
@model MbmStore.ViewModels.ShippingDetails
@{
    ViewBag.Title = "MusicBookMovie Store: Checkout";
}
<h2>Check out now</h2>
<p>Please enter your details, and we'll ship your goods right away!</p>
@using (Html.BeginForm())
{
    <h3>Ship to</h3>

    foreach (var property in ViewData.ModelMetadata.Properties)
    {
        if (property.PropertyName != "GiftWrap")
        {
            <div class="form-group">
                <label>@(property.DisplayName ?? property.PropertyName)</label>
                @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
            </div>
        }
    }

    <h3>Options</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.GiftWrap)
            Gift wrap these items
        </label>
    </div>
    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Complete order" />
    </div>
}

MbmStore-start/MbmStore/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "MusicBookMovie Store: Order Submitted";
}
<h2>Thanks!</h2>
Thanks for placing your order. We'll ship your goods as soon as possible.

MbmStore-start/MbmStore/Views/Cart/Index.cshtml
@model MbmStore.ViewModels.CartIndexViewModel
@{
    ViewBag.Title = "MusicBookMovieStore: Your Cart";
}
<h2>Your cart</h2>
<table class="table">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Product.Title</td>
                <td class="text-right">@line.Product.Price.ToString("n")</td>
                <td class="text-right">
                    @((line.Quantity * line.Product.Price).ToString("n"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("ProductId", line.Product.ProductId)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Remove" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.Cart.TotalPrice.ToString("n")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    @Html.ActionLink("Continue Shopping", "Index", "Catalogue", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Checkout now", "Checkout", null, new { @class = "btn btn-primary" })
</div>